### ISSUE TITLE
reviewdog: -fail-on-error is deprecated

### ISSUE THREAD

**Issue by rfay** [UmbrellaDocs/action-linkspector#33]
**Describe the bug**

Reviewdog is reporting "-fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead":

`msg="reviewdog: -fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead. See also https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md"`

**To Reproduce**

I think this shows on every action-linkinspector run.

But see https://github.com/ddev/ddev/actions/runs/12507322469/job/34893657216#step:9:261

**Expected behavior**

No deprecation warning.

**Screenshots**

**Additional context**

I tried to find how reviewdog is being run to resolve this but didn't find it.

**Comment by Realiserad** [comment]
Duplicate of #24.

**Comment by rfay** [comment]
CLosing in favor of
* #24
